name: "Build and Release"
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: any
          flutter-version: 3.x
      - run: flutter --version
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter build apk --release
      - name: "Upload APK"
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0.${{ github.run_number}}
          token: ${{ secrets.TOKEN }}
      - name: "Upload and Release APK"
        uses: ncipollo/release-action@v1
        with:
          artifacts: app-release
          token: ${{ secrets.TOKEN }}
          tag: v1.0.${{ github.run_number}}
